:- [main].

debug_prvr(vampire).

debug_hints([mtrx]).

debug_ctx([(sf224,(+ ? ? (~ (use^[])=(a_select3^[z_defuse^[],#(1),#(0)])&(~ (pv5^[])= #(0)|~ (n2^[])= #(1))&(~ (pv5^[])= #(0)|~ (n1^[])= #(1))&(~ (pv5^[])= #(0)|~ (n0^[])= #(1))&leq(#(0),pv5^[])&leq(#(1),n2^[])&leq(n0^[],#(0))&leq(n0^[],#(1)))&!! ((use^[])=(a_select3^[z_defuse^[],#(1),#(0)])|~leq(#(0),pred^[pv5^[]])|~leq(#(1),n2^[])|~leq(n0^[],#(0))|~leq(n0^[],#(1)))&!! ((use^[])=(a_select3^[u_defuse^[],#(1),#(0)])|~leq(#(0),pred^[pv5^[]])|~leq(#(1),n2^[])|~leq(n0^[],#(0))|~leq(n0^[],#(1)))&gt(pv5^[],n0^[])&leq(pv5^[],n998^[])&leq(pv5^[],n0^[])&leq(n0^[],pv5^[])&(use^[])=(a_select2^[xinit_noise_defuse^[],n5^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n4^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n3^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n2^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n1^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n0^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n5^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n4^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n3^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n2^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n1^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n0^[]])&(use^[])=(a_select2^[xinit_defuse^[],n5^[]])&(use^[])=(a_select2^[xinit_defuse^[],n4^[]])&(use^[])=(a_select2^[xinit_defuse^[],n3^[]])&(use^[])=(a_select3^[u_defuse^[],n2^[],n0^[]])&(use^[])=(a_select3^[u_defuse^[],n1^[],n0^[]])&(use^[])=(a_select3^[u_defuse^[],n0^[],n0^[]])&(use^[])=(a_select2^[sigma_defuse^[],n5^[]])&(use^[])=(a_select2^[sigma_defuse^[],n4^[]])&(use^[])=(a_select2^[sigma_defuse^[],n3^[]])&(use^[])=(a_select2^[sigma_defuse^[],n2^[]])&(use^[])=(a_select2^[sigma_defuse^[],n1^[]])&(use^[])=(a_select2^[sigma_defuse^[],n0^[]])&(use^[])=(a_select2^[rho_defuse^[],n2^[]])&(use^[])=(a_select2^[rho_defuse^[],n1^[]])&(use^[])=(a_select2^[rho_defuse^[],n0^[]]))),(sf225,(+ ? ? (~ (use^[])=(a_select3^[z_defuse^[],#(1),#(0)])&(~ (pv5^[])= #(0)|~ (n2^[])= #(1))&(~ (pv5^[])= #(0)|~ (n1^[])= #(1))&(~ (pv5^[])= #(0)|~ (n0^[])= #(1))&leq(#(0),pv5^[])&leq(#(1),n2^[])&leq(n0^[],#(0))&leq(n0^[],#(1)))=> ~ (use^[])=(a_select3^[z_defuse^[],sK31^[],sK32^[]])&(~ (pv5^[])=(sK32^[])|~ (n2^[])=(sK31^[]))&(~ (pv5^[])=(sK32^[])|~ (n1^[])=(sK31^[]))&(~ (pv5^[])=(sK32^[])|~ (n0^[])=(sK31^[]))&leq(sK32^[],pv5^[])&leq(sK31^[],n2^[])&leq(n0^[],sK32^[])&leq(n0^[],sK31^[])))]).

debug_hyp((sf226,(- (~ (use^[])=(a_select3^[z_defuse^[],sK31^[],sK32^[]])&(~ (pv5^[])=(sK32^[])|~ (n2^[])=(sK31^[]))&(~ (pv5^[])=(sK32^[])|~ (n1^[])=(sK31^[]))&(~ (pv5^[])=(sK32^[])|~ (n0^[])=(sK31^[]))&leq(sK32^[],pv5^[])&leq(sK31^[],n2^[])&leq(n0^[],sK32^[])&leq(n0^[],sK31^[]))&!! ((use^[])=(a_select3^[z_defuse^[],#(1),#(0)])|~leq(#(0),pred^[pv5^[]])|~leq(#(1),n2^[])|~leq(n0^[],#(0))|~leq(n0^[],#(1)))&!! ((use^[])=(a_select3^[u_defuse^[],#(1),#(0)])|~leq(#(0),pred^[pv5^[]])|~leq(#(1),n2^[])|~leq(n0^[],#(0))|~leq(n0^[],#(1)))&gt(pv5^[],n0^[])&leq(pv5^[],n998^[])&leq(pv5^[],n0^[])&leq(n0^[],pv5^[])&(use^[])=(a_select2^[xinit_noise_defuse^[],n5^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n4^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n3^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n2^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n1^[]])&(use^[])=(a_select2^[xinit_noise_defuse^[],n0^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n5^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n4^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n3^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n2^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n1^[]])&(use^[])=(a_select2^[xinit_mean_defuse^[],n0^[]])&(use^[])=(a_select2^[xinit_defuse^[],n5^[]])&(use^[])=(a_select2^[xinit_defuse^[],n4^[]])&(use^[])=(a_select2^[xinit_defuse^[],n3^[]])&(use^[])=(a_select3^[u_defuse^[],n2^[],n0^[]])&(use^[])=(a_select3^[u_defuse^[],n1^[],n0^[]])&(use^[])=(a_select3^[u_defuse^[],n0^[],n0^[]])&(use^[])=(a_select2^[sigma_defuse^[],n5^[]])&(use^[])=(a_select2^[sigma_defuse^[],n4^[]])&(use^[])=(a_select2^[sigma_defuse^[],n3^[]])&(use^[])=(a_select2^[sigma_defuse^[],n2^[]])&(use^[])=(a_select2^[sigma_defuse^[],n1^[]])&(use^[])=(a_select2^[sigma_defuse^[],n0^[]])&(use^[])=(a_select2^[rho_defuse^[],n2^[]])&(use^[])=(a_select2^[rho_defuse^[],n1^[]])&(use^[])=(a_select2^[rho_defuse^[],n0^[]])))).

debug_goal((_103842,0,0)).

